name: citiasia
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.11.0
  get: 4.6.5
  auto_size_text: ^3.0.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
