name: citiasia
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  font_awesome_flutter: ^10.2.1
  get: 4.6.5
  get_cli: ^1.8.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
